# -*- coding: utf-8 -*-
"""skinnet-cancer-classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOvXFliaCLQAsyMYchAc5Mpw3nCgjMx7

PASSO 1 — Montar Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

metadata_path = '/content/drive/MyDrive/tcc_skin_cancer/HAM10000_metadata.csv'

df = pd.read_csv(metadata_path)

df.head()

df['dx'].value_counts()

import os
from glob import glob

image_path_1 = '/content/drive/MyDrive/tcc_skin_cancer/ham10000_images_part_1/*.jpg'
image_path_2 = '/content/drive/MyDrive/tcc_skin_cancer/ham10000_images_part_2/*.jpg'

all_image_paths = glob(image_path_1) + glob(image_path_2)

print("Quantidade de imagens encontradas:", len(all_image_paths))

imageid_path_dict = {
    os.path.splitext(os.path.basename(x))[0]: x
    for x in all_image_paths
}

df['path'] = df['image_id'].map(imageid_path_dict.get)

df[['image_id', 'path']].head()

from PIL import Image
import matplotlib.pyplot as plt

sample = df.iloc[0]

img = Image.open(sample['path'])

plt.figure(figsize=(5,5))
plt.imshow(img)
plt.title(f"Classe: {sample['dx']}")
plt.axis('off')
plt.show()

fig, axes = plt.subplots(2, 4, figsize=(15, 8))

classes = df['dx'].unique()

for ax, lesion in zip(axes.flatten(), classes):

    sample = df[df['dx'] == lesion].iloc[0]

    img = Image.open(sample['path'])

    ax.imshow(img)
    ax.set_title(lesion)
    ax.axis('off')

plt.tight_layout()
plt.show()

lesion_type_dict = {
    'nv': 'Melanocytic nevi',
    'mel': 'Melanoma',
    'bkl': 'Benign keratosis-like lesions',
    'bcc': 'Basal cell carcinoma',
    'akiec': 'Actinic keratoses',
    'vasc': 'Vascular lesions',
    'df': 'Dermatofibroma'
}

df['lesion_type'] = df['dx'].map(lesion_type_dict)

print(df.columns)
df[['image_id', 'dx', 'lesion_type', 'binary_label', 'binary_label_name', 'path']].head()

suspect_classes = ['mel', 'bcc', 'akiec']

df['binary_label'] = df['dx'].apply(lambda x: 1 if x in suspect_classes else 0)

df['binary_label'].value_counts()

df['binary_label_name'] = df['binary_label'].map({
    0: 'nao_suspeito',
    1: 'suspeito'
})

df[['image_id', 'dx', 'lesion_type', 'binary_label', 'binary_label_name', 'path']].head()

from sklearn.model_selection import train_test_split
train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    stratify=df['binary_label'],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df['binary_label'],
    random_state=42
)

print("Treino:", len(train_df))
print("Validação:", len(val_df))
print("Teste:", len(test_df))

print("\nTreino")
print(train_df['binary_label'].value_counts(normalize=True))

print("\nValidação")
print(val_df['binary_label'].value_counts(normalize=True))

print("\nTeste")
print(test_df['binary_label'].value_counts(normalize=True))

train_df['binary_label_name'] = train_df['binary_label_name'].astype(str)
val_df['binary_label_name'] = val_df['binary_label_name'].astype(str)
test_df['binary_label_name'] = test_df['binary_label_name'].astype(str)

from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE = 224
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True
)

val_test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_dataframe(
    dataframe=train_df,
    x_col='path',
    y_col='binary_label_name',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    shuffle=True
)

val_generator = val_test_datagen.flow_from_dataframe(
    dataframe=val_df,
    x_col='path',
    y_col='binary_label_name',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    shuffle=False
)

test_generator = val_test_datagen.flow_from_dataframe(
    dataframe=test_df,
    x_col='path',
    y_col='binary_label_name',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    shuffle=False
)

import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Input(shape=(224, 224, 3)),

    layers.Conv2D(32, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),

    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=5
)

import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

test_generator.reset()

pred_probs = model.predict(test_generator)
pred_classes = (pred_probs > 0.5).astype(int).ravel()

true_classes = test_generator.classes

print(classification_report(true_classes, pred_classes, target_names=['nao_suspeito', 'suspeito']))

print(confusion_matrix(true_classes, pred_classes))

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_df['binary_label']),
    y=train_df['binary_label']
)

class_weights = dict(enumerate(class_weights))

print(class_weights)

history_weighted = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=5,
    class_weight=class_weights
)

test_generator.reset()

pred_probs = model.predict(test_generator)
pred_classes = (pred_probs > 0.5).astype(int).ravel()

true_classes = test_generator.classes

print(classification_report(true_classes, pred_classes, target_names=['nao_suspeito', 'suspeito']))
print(confusion_matrix(true_classes, pred_classes))

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.resnet50 import preprocess_input

train_datagen_resnet = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=20,
    zoom_range=0.15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True
)

val_test_datagen_resnet = ImageDataGenerator(
    preprocessing_function=preprocess_input
)

train_generator_resnet = train_datagen_resnet.flow_from_dataframe(
    dataframe=train_df,
    x_col='path',
    y_col='binary_label_name',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    shuffle=True
)

val_generator_resnet = val_test_datagen_resnet.flow_from_dataframe(
    dataframe=val_df,
    x_col='path',
    y_col='binary_label_name',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    shuffle=False
)

test_generator_resnet = val_test_datagen_resnet.flow_from_dataframe(
    dataframe=test_df,
    x_col='path',
    y_col='binary_label_name',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    shuffle=False
)

from tensorflow.keras.applications import ResNet50
from tensorflow.keras import layers, models

base_model = ResNet50(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)

base_model.trainable = False

resnet_model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

resnet_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

resnet_model.summary()

history_resnet = resnet_model.fit(
    train_generator_resnet,
    validation_data=val_generator_resnet,
    epochs=5,
    class_weight=class_weights
)

test_generator_resnet.reset()

pred_probs_resnet = resnet_model.predict(test_generator_resnet)
pred_classes_resnet = (pred_probs_resnet > 0.5).astype(int).ravel()

true_classes_resnet = test_generator_resnet.classes

print(classification_report(true_classes_resnet, pred_classes_resnet, target_names=['nao_suspeito', 'suspeito']))
print(confusion_matrix(true_classes_resnet, pred_classes_resnet))

import os

MODEL_DIR = '/content/drive/MyDrive/tcc_skin_cancer/models'
os.makedirs(MODEL_DIR, exist_ok=True)

resnet_model.save(f'{MODEL_DIR}/resnet50_transfer_learning_baseline.keras')

os.listdir(MODEL_DIR)

base_model.trainable = True

for layer in base_model.layers[:-30]:
    layer.trainable = False

from tensorflow.keras.optimizers import Adam

resnet_model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_resnet_finetune = resnet_model.fit(
    train_generator_resnet,
    validation_data=val_generator_resnet,
    epochs=5,
    class_weight=class_weights
)

test_generator_resnet.reset()

pred_probs_finetune = resnet_model.predict(test_generator_resnet)
pred_classes_finetune = (pred_probs_finetune > 0.5).astype(int).ravel()

true_classes_finetune = test_generator_resnet.classes

print(classification_report(true_classes_finetune, pred_classes_finetune, target_names=['nao_suspeito', 'suspeito']))
print(confusion_matrix(true_classes_finetune, pred_classes_finetune))

resnet_model.save(f'{MODEL_DIR}/resnet50_finetuned.keras')

os.listdir(MODEL_DIR)

for layer in base_model.layers[::-1]:
    if 'conv' in layer.name:
        print(layer.name)
        break

last_conv_layer_name = "conv5_block3_out"

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input
from PIL import Image

def make_gradcam_heatmap(img_array, model, last_conv_layer_name):
    base_model = model.layers[0]

    grad_model = tf.keras.models.Model(
        inputs=base_model.input,
        outputs=[
            base_model.get_layer(last_conv_layer_name).output,
            model.output
        ]
    )

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        loss = predictions[:, 0]

    grads = tape.gradient(loss, conv_outputs)

    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    conv_outputs = conv_outputs[0]

    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    heatmap = tf.maximum(heatmap, 0) / tf.math.reduce_max(heatmap)

    return heatmap.numpy()

def display_gradcam(img_path, model, last_conv_layer_name, alpha=0.4):
    img = Image.open(img_path).resize((224, 224)).convert("RGB")
    img_array = image.img_to_array(img)
    img_array_expanded = np.expand_dims(img_array, axis=0)
    img_array_preprocessed = preprocess_input(img_array_expanded.copy())

    heatmap = make_gradcam_heatmap(
        img_array_preprocessed,
        model,
        last_conv_layer_name
    )

    heatmap_resized = Image.fromarray(np.uint8(255 * heatmap)).resize((224, 224))
    heatmap_resized = np.array(heatmap_resized)

    plt.figure(figsize=(10, 4))

    plt.subplot(1, 2, 1)
    plt.imshow(img)
    plt.title("Imagem original")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(img)
    plt.imshow(heatmap_resized, cmap="jet", alpha=alpha)
    plt.title("Grad-CAM")
    plt.axis("off")

    plt.show()

sample_suspect = test_df[test_df['binary_label'] == 1].iloc[0]

display_gradcam(
    sample_suspect['path'],
    resnet_model,
    last_conv_layer_name
)

dummy = np.zeros((1, 224, 224, 3), dtype=np.float32)
_ = resnet_model(dummy)

def make_gradcam_heatmap(img_array, model, last_conv_layer_name):
    base_model = model.layers[0]

    conv_layer = base_model.get_layer(last_conv_layer_name)

    grad_model = tf.keras.models.Model(
        inputs=model.inputs,
        outputs=[
            conv_layer.output,
            model.output
        ]
    )

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        loss = predictions[:, 0]

    grads = tape.gradient(loss, conv_outputs)

    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    conv_outputs = conv_outputs[0]

    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    heatmap = tf.maximum(heatmap, 0)

    max_val = tf.reduce_max(heatmap)

    if max_val == 0:
        return heatmap.numpy()

    heatmap /= max_val

    return heatmap.numpy()


def display_gradcam(img_path, model, last_conv_layer_name, alpha=0.4):
    img = Image.open(img_path).resize((224, 224)).convert("RGB")

    img_array = image.img_to_array(img)

    img_array_expanded = np.expand_dims(img_array, axis=0)

    img_array_preprocessed = preprocess_input(img_array_expanded.copy())

    heatmap = make_gradcam_heatmap(
        img_array_preprocessed,
        model,
        last_conv_layer_name
    )

    heatmap_resized = Image.fromarray(
        np.uint8(255 * heatmap)
    ).resize((224, 224))

    heatmap_resized = np.array(heatmap_resized)

    plt.figure(figsize=(10, 4))

    plt.subplot(1, 2, 1)
    plt.imshow(img)
    plt.title("Imagem original")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(img)
    plt.imshow(heatmap_resized, cmap="jet", alpha=alpha)
    plt.title("Grad-CAM")
    plt.axis("off")

    plt.show()


sample_suspect = test_df[test_df['binary_label'] == 1].iloc[0]

display_gradcam(
    sample_suspect['path'],
    resnet_model,
    last_conv_layer_name
)

def make_gradcam_heatmap(img_array, model, last_conv_layer_name):
    base_model = model.layers[0]

    inputs = base_model.input
    x = base_model.output

    for layer in model.layers[1:]:
        try:
            x = layer(x, training=False)
        except:
            x = layer(x)

    grad_model = tf.keras.models.Model(
        inputs=inputs,
        outputs=[
            base_model.get_layer(last_conv_layer_name).output,
            x
        ]
    )

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        loss = predictions[:, 0]

    grads = tape.gradient(loss, conv_outputs)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    conv_outputs = conv_outputs[0]

    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    heatmap = tf.maximum(heatmap, 0)
    heatmap = heatmap / (tf.reduce_max(heatmap) + 1e-8)

    return heatmap.numpy()


def display_gradcam(img_path, model, last_conv_layer_name, alpha=0.4):
    img = Image.open(img_path).resize((224, 224)).convert("RGB")

    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array.copy())

    heatmap = make_gradcam_heatmap(
        img_array,
        model,
        last_conv_layer_name
    )

    heatmap = Image.fromarray(np.uint8(255 * heatmap)).resize((224, 224))
    heatmap = np.array(heatmap)

    plt.figure(figsize=(10, 4))

    plt.subplot(1, 2, 1)
    plt.imshow(img)
    plt.title("Imagem original")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(img)
    plt.imshow(heatmap, cmap="jet", alpha=alpha)
    plt.title("Grad-CAM")
    plt.axis("off")

    plt.show()


sample_suspect = test_df[test_df['binary_label'] == 1].iloc[0]

display_gradcam(
    sample_suspect['path'],
    resnet_model,
    "conv5_block3_out"
)

test_results_df = test_df.copy().reset_index(drop=True)

test_results_df['true_label'] = true_classes_finetune
test_results_df['pred_label'] = pred_classes_finetune
test_results_df['pred_prob'] = pred_probs_finetune.ravel()

test_results_df.head()

true_positive = test_results_df[
    (test_results_df['true_label'] == 1) &
    (test_results_df['pred_label'] == 1)
]

true_negative = test_results_df[
    (test_results_df['true_label'] == 0) &
    (test_results_df['pred_label'] == 0)
]

false_positive = test_results_df[
    (test_results_df['true_label'] == 0) &
    (test_results_df['pred_label'] == 1)
]

false_negative = test_results_df[
    (test_results_df['true_label'] == 1) &
    (test_results_df['pred_label'] == 0)
]

print("Verdadeiro positivo:", len(true_positive))
print("Verdadeiro negativo:", len(true_negative))
print("Falso positivo:", len(false_positive))
print("Falso negativo:", len(false_negative))

sample_tp = true_positive.iloc[0]

display_gradcam(
    sample_tp['path'],
    resnet_model,
    "conv5_block3_out"
)

print(sample_tp[['dx', 'pred_prob']])

sample_tn = true_negative.iloc[0]

display_gradcam(
    sample_tn['path'],
    resnet_model,
    "conv5_block3_out"
)

print(sample_tn[['dx', 'pred_prob']])

sample_fp = false_positive.iloc[0]

display_gradcam(
    sample_fp['path'],
    resnet_model,
    "conv5_block3_out"
)

print(sample_fp[['dx', 'pred_prob']])

sample_fn = false_negative.iloc[0]

display_gradcam(
    sample_fn['path'],
    resnet_model,
    "conv5_block3_out"
)

print(sample_fn[['dx', 'pred_prob']])

resnet_model.save(f'{MODEL_DIR}/resnet50_finetuned.keras')

RESULTS_DIR = '/content/drive/MyDrive/tcc_skin_cancer/results'
os.makedirs(RESULTS_DIR, exist_ok=True)

import pandas as pd

metrics_data = [
    {
        "modelo": "CNN baseline",
        "accuracy": 0.81,
        "precision_suspeito": 0.00,
        "recall_suspeito": 0.00,
        "f1_suspeito": 0.00
    },
    {
        "modelo": "ResNet50 Transfer Learning",
        "accuracy": 0.79,
        "precision_suspeito": 0.47,
        "recall_suspeito": 0.86,
        "f1_suspeito": 0.61
    },
    {
        "modelo": "ResNet50 Fine Tuned",
        "accuracy": 0.86,
        "precision_suspeito": 0.60,
        "recall_suspeito": 0.77,
        "f1_suspeito": 0.68
    }
]

metrics_df = pd.DataFrame(metrics_data)
metrics_df.to_csv(f'{RESULTS_DIR}/metrics_comparison.csv', index=False)

metrics_df

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

cm_finetune = confusion_matrix(true_classes_finetune, pred_classes_finetune)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_finetune,
    display_labels=['nao_suspeito', 'suspeito']
)

disp.plot(values_format='d')
plt.title('Matriz de Confusão - ResNet50 Fine Tuned')
plt.savefig(f'{RESULTS_DIR}/confusion_matrix_resnet50_finetuned.png', dpi=300, bbox_inches='tight')
plt.show()

import os

BASE_DIR = '/content/drive/MyDrive/tcc_skin_cancer'
MODEL_DIR = f'{BASE_DIR}/models'
RESULTS_DIR = f'{BASE_DIR}/results'
GRADCAM_DIR = f'{RESULTS_DIR}/gradcam_examples'

os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(GRADCAM_DIR, exist_ok=True)

model.save(f'{MODEL_DIR}/cnn_baseline.keras')
resnet_model.save(f'{MODEL_DIR}/resnet50_finetuned.keras')

metrics_data = [
    {
        "modelo": "CNN baseline",
        "accuracy": 0.81,
        "precision_suspeito": 0.00,
        "recall_suspeito": 0.00,
        "f1_suspeito": 0.00,
        "tn": 1210,
        "fp": 0,
        "fn": 293,
        "tp": 0
    },
    {
        "modelo": "ResNet50 Transfer Learning",
        "accuracy": 0.79,
        "precision_suspeito": 0.47,
        "recall_suspeito": 0.86,
        "f1_suspeito": 0.61,
        "tn": 927,
        "fp": 283,
        "fn": 40,
        "tp": 253
    },
    {
        "modelo": "ResNet50 Fine Tuned",
        "accuracy": 0.86,
        "precision_suspeito": 0.60,
        "recall_suspeito": 0.77,
        "f1_suspeito": 0.68,
        "tn": 1063,
        "fp": 147,
        "fn": 68,
        "tp": 225
    }
]

metrics_df = pd.DataFrame(metrics_data)
metrics_df.to_csv(f'{RESULTS_DIR}/metrics_comparison.csv', index=False)
metrics_df

from sklearn.metrics import classification_report, confusion_matrix
import json

report_finetune = classification_report(
    true_classes_finetune,
    pred_classes_finetune,
    target_names=['nao_suspeito', 'suspeito'],
    output_dict=True
)

with open(f'{RESULTS_DIR}/classification_report_resnet50_finetuned.json', 'w') as f:
    json.dump(report_finetune, f, indent=4)

pd.DataFrame(report_finetune).transpose().to_csv(
    f'{RESULTS_DIR}/classification_report_resnet50_finetuned.csv'
)

predictions_df = test_results_df.copy()
predictions_df.to_csv(f'{RESULTS_DIR}/test_predictions_resnet50_finetuned.csv', index=False)

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

cm_finetune = confusion_matrix(true_classes_finetune, pred_classes_finetune)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_finetune,
    display_labels=['nao_suspeito', 'suspeito']
)

disp.plot(values_format='d')
plt.title('Matriz de Confusão - ResNet50 Fine Tuned')
plt.savefig(f'{RESULTS_DIR}/confusion_matrix_resnet50_finetuned.png', dpi=300, bbox_inches='tight')
plt.show()

history_df = pd.DataFrame(history_resnet_finetune.history)
history_df.to_csv(f'{RESULTS_DIR}/history_resnet50_finetuned.csv', index=False)

plt.figure(figsize=(8,5))
plt.plot(history_resnet_finetune.history['accuracy'], label='Treino')
plt.plot(history_resnet_finetune.history['val_accuracy'], label='Validação')
plt.title('Acurácia - ResNet50 Fine Tuned')
plt.xlabel('Época')
plt.ylabel('Acurácia')
plt.legend()
plt.savefig(f'{RESULTS_DIR}/accuracy_resnet50_finetuned.png', dpi=300, bbox_inches='tight')
plt.show()

plt.figure(figsize=(8,5))
plt.plot(history_resnet_finetune.history['loss'], label='Treino')
plt.plot(history_resnet_finetune.history['val_loss'], label='Validação')
plt.title('Loss - ResNet50 Fine Tuned')
plt.xlabel('Época')
plt.ylabel('Loss')
plt.legend()
plt.savefig(f'{RESULTS_DIR}/loss_resnet50_finetuned.png', dpi=300, bbox_inches='tight')
plt.show()

experiment_metadata = {
    "author": "Lucas Marques",
    "project": "Classificação Computacional de Lesões Cutâneas Sugestivas de Câncer de Pele",
    "dataset": "HAM10000",
    "total_images": 10015,
    "task": "Classificação binária",
    "classes": {
        "0": "nao_suspeito",
        "1": "suspeito"
    },
    "suspect_classes": ["mel", "bcc", "akiec"],
    "non_suspect_classes": ["nv", "bkl", "vasc", "df"],
    "train_size": len(train_df),
    "validation_size": len(val_df),
    "test_size": len(test_df),
    "best_model": "ResNet50 Fine Tuned",
    "best_model_file": "resnet50_finetuned.keras",
    "image_size": "224x224",
    "framework": "TensorFlow/Keras"
}

with open(f'{RESULTS_DIR}/experiment_metadata.json', 'w') as f:
    json.dump(experiment_metadata, f, indent=4)

print("Modelos:")
print(os.listdir(MODEL_DIR))

print("\nResultados:")
print(os.listdir(RESULTS_DIR))

from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.optimizers import Adam

train_datagen_eff = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=20,
    zoom_range=0.15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True
)

val_test_datagen_eff = ImageDataGenerator(
    preprocessing_function=preprocess_input
)

train_generator_eff = train_datagen_eff.flow_from_dataframe(
    dataframe=train_df,
    x_col='path',
    y_col='binary_label_name',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    shuffle=True
)

val_generator_eff = val_test_datagen_eff.flow_from_dataframe(
    dataframe=val_df,
    x_col='path',
    y_col='binary_label_name',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    shuffle=False
)

test_generator_eff = val_test_datagen_eff.flow_from_dataframe(
    dataframe=test_df,
    x_col='path',
    y_col='binary_label_name',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    shuffle=False
)

base_eff = EfficientNetB0(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)

base_eff.trainable = False

eff_model = tf.keras.Sequential([
    base_eff,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

eff_model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_eff = eff_model.fit(
    train_generator_eff,
    validation_data=val_generator_eff,
    epochs=5,
    class_weight=class_weights
)

from sklearn.metrics import classification_report, confusion_matrix

test_generator_eff.reset()

pred_probs_eff = eff_model.predict(test_generator_eff)
pred_classes_eff = (pred_probs_eff > 0.5).astype(int).ravel()

true_classes_eff = test_generator_eff.classes

print(classification_report(
    true_classes_eff,
    pred_classes_eff,
    target_names=['nao_suspeito', 'suspeito']
))

print(confusion_matrix(true_classes_eff, pred_classes_eff))

eff_model.save(f'{MODEL_DIR}/efficientnetb0.keras')

metrics_data = [
    {
        "modelo": "CNN baseline",
        "accuracy": 0.81,
        "precision_suspeito": 0.00,
        "recall_suspeito": 0.00,
        "f1_suspeito": 0.00
    },
    {
        "modelo": "ResNet50 Transfer Learning",
        "accuracy": 0.79,
        "precision_suspeito": 0.47,
        "recall_suspeito": 0.86,
        "f1_suspeito": 0.61
    },
    {
        "modelo": "ResNet50 Fine Tuned",
        "accuracy": 0.86,
        "precision_suspeito": 0.60,
        "recall_suspeito": 0.77,
        "f1_suspeito": 0.68
    },
    {
        "modelo": "EfficientNetB0",
        "accuracy": 0.77,
        "precision_suspeito": 0.45,
        "recall_suspeito": 0.79,
        "f1_suspeito": 0.58
    }
]

metrics_df = pd.DataFrame(metrics_data)

metrics_df.to_csv(
    f'{RESULTS_DIR}/metrics_comparison.csv',
    index=False
)

metrics_df

import matplotlib.pyplot as plt
import numpy as np

models_names = metrics_df['modelo']

x = np.arange(len(models_names))
width = 0.2

fig, ax = plt.subplots(figsize=(12,6))

ax.bar(x - width, metrics_df['accuracy'], width, label='Accuracy')
ax.bar(x, metrics_df['recall_suspeito'], width, label='Recall')
ax.bar(x + width, metrics_df['f1_suspeito'], width, label='F1-score')

ax.set_ylabel('Score')
ax.set_title('Comparação entre Modelos')
ax.set_xticks(x)
ax.set_xticklabels(models_names, rotation=10)

ax.legend()

plt.tight_layout()

plt.savefig(
    f'{RESULTS_DIR}/models_comparison.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

history_eff_df = pd.DataFrame(history_eff.history)

history_eff_df.to_csv(
    f'{RESULTS_DIR}/history_efficientnet.csv',
    index=False
)

report_eff = classification_report(
    true_classes_eff,
    pred_classes_eff,
    target_names=['nao_suspeito', 'suspeito'],
    output_dict=True
)

pd.DataFrame(report_eff).transpose().to_csv(
    f'{RESULTS_DIR}/classification_report_efficientnet.csv'
)

import os

def save_gradcam(img_path, model, last_conv_layer_name, output_path, alpha=0.4):

    img = Image.open(img_path).resize((224, 224)).convert("RGB")

    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array.copy())

    heatmap = make_gradcam_heatmap(
        img_array,
        model,
        last_conv_layer_name
    )

    heatmap = Image.fromarray(
        np.uint8(255 * heatmap)
    ).resize((224, 224))

    heatmap = np.array(heatmap)

    plt.figure(figsize=(10,4))

    plt.subplot(1,2,1)
    plt.imshow(img)
    plt.title("Original")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(img)
    plt.imshow(heatmap, cmap='jet', alpha=alpha)
    plt.title("Grad-CAM")
    plt.axis("off")

    plt.tight_layout()

    plt.savefig(output_path, dpi=300, bbox_inches='tight')

    plt.close()

save_gradcam(
    sample_tp['path'],
    resnet_model,
    "conv5_block3_out",
    f"{GRADCAM_DIR}/true_positive.png"
)

save_gradcam(
    sample_tn['path'],
    resnet_model,
    "conv5_block3_out",
    f"{GRADCAM_DIR}/true_negative.png"
)

save_gradcam(
    sample_fp['path'],
    resnet_model,
    "conv5_block3_out",
    f"{GRADCAM_DIR}/false_positive.png"
)

save_gradcam(
    sample_fn['path'],
    resnet_model,
    "conv5_block3_out",
    f"{GRADCAM_DIR}/false_negative.png"
)

os.listdir(GRADCAM_DIR)